<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE p[
  <!ELEMENT p (transactions+)>
  <!ELEMENT transactions (person_id, animal_id, summa)>
  <!ATTLIST transactions transactionsId ID #REQUIRED>
  <!ELEMENT person_id (#PCDATA)>
  <!ELEMENT animal_id (#PCDATA)>
  <!ELEMENT summa (#PCDATA)>	
]>

<p>
<?refreshData daily?>
<![CDATA[<?xml version="1.0"?>]]>

  <transactions transactionsId = "5">
    <person_id>300</person_id>
    <animal_id>10</animal_id>
    <summa>30.8</summa>
  </transactions>
  <transactions transactionsId = "10">
    <person_id>2</person_id>
    <animal_id>10</animal_id>
    <summa>35.6</summa>
  </transactions>
  <transactions transactionsId = "35">
    <person_id>2</person_id>
    <animal_id>6</animal_id>
    <summa>5.7</summa>
  </transactions>  
  <transactions transactionsId = "26">
    <person_id>202</person_id>
    <animal_id>23</animal_id>
    <summa>34.6</summa>
  </transactions>
  <transactions transactionsId = "40">
    <person_id>17</person_id>
    <animal_id>10</animal_id>
    <summa>20.7</summa>
  </transactions>
  <transactions transactionsId = "200">
    <person_id>3</person_id>
    <animal_id>6</animal_id>
    <summa>5.8</summa>
  </transactions>
</p>